### ISSUE TITLE
Addin elevation data to LuSTScenario

### ISSUE THREAD

**Issue by coloal** [lcodeca/LuSTScenario#10]
How changed is LuSTScenario from the real Luxemburg? I need to add elevation data to the scenario but it looks pretty difficult to adapt the data of an osm of Luxemburg, with 3D information, to this scenario.

**Comment by lcodeca** [comment]
The OSM map used is from 2014 and it's heavily changed to achieve a smooth simulation. Now SUMO largely improved and it requires fewer modifications, but at the time, it was different.
Anyway, the only thing that you can do it's to try and see if it fits. I spoke with others that tried it, but I don't know how complex was it for them and from what elevation datasets they started.  You can try to contact the authors of http://dl.ifip.org/db/conf/wons/wons2018/12-11-On-the-Necessity-Brummer-5188217.pdf and see if they can help you.
