### ISSUE TITLE
Limit Number of Vehicles and Increase Messages Transmitted

### ISSUE THREAD

**Issue by tabaddor** [lcodeca/LuSTScenario#11]
I am currently using the VeReMi configuration for OMNET++, Veins, and SUMO which uses the LUST scenario. Is there any way to limit the number of vehicles as well as increase the number of transmissions a vehicle receives? It seems as if hundreds of vehicles are being created in a simulation whereas I prefer a small number of vehicles transmitting messages to each other over a long period of time (~a few hours). 

How can I accomplish this?

**Comment by lcodeca** [comment]
Hello, you should ask the authors of VeReMi.
I don't know what it is, so I cannot help.
