### ISSUE TITLE
How to add a car that won't reroute

### ISSUE THREAD

**Issue by zhl555** [lcodeca/LuSTScenario#12]
hello,

I would like to add a car into this dataset, but when I am given a certain path, the ego car tends to rerouting.

I want to add a car in this dataset, it only follows the path I give, and the path will not be redefined, how can I achieve this?

**Comment by lcodeca** [comment]
This is a SUMO question, so I would read more in its documentation.
Nonetheless, you can do as I did here: https://github.com/lcodeca/MoSTScenario/blob/master/scenario/in/add/basic.vType.xml#L23
