### ISSUE TITLE
Dynamic Rerouting

### ISSUE THREAD

**Issue by pierredefermat** [lcodeca/LuSTScenario#2]
Hi
Thanks for the wonderful work that you have put into this project. Is there a specific reason why you have enabled dynamic rerouting while, providing specific routes, which I assume were achieved after doing the dynamic user equilibrium process?
Should we (users) do a DUE loop before we use it for doing additional analysis?

Thanks

**Comment by lcodeca** [comment]
Sorry for the delay in the answer.
DUA routes are shortest path from origin to destination, ant this is not an equilibrium.
DUE routes represent the dynamic user equilibrium, and there is no need to optimise them.
