### ISSUE TITLE
Example for connecting to omnet++ with veins

### ISSUE THREAD

**Issue by joakimb** [lcodeca/LuSTScenario#7]
Thanks for this repo!

I am having trouble using this scenario in omnet++ via veins. Specifically I do not manage to produce a launchd.xml. In your paper you describe having run this with omnet++ and veins. 

Is this code, or other similar example code, available anywhere. Otherwise, could it be made available?

**Comment by namnatulco** [comment]
We used the LuST scenario in one of our papers, the configuration can be found here:
https://github.com/VeReMi-dataset/veins/tree/securecomm2018/simulations/securecomm2018
I think (but I might be remembering wrong...) that I manually created the launchd.xml.

**Comment by lcodeca** [comment]
Thank you Rens for the link. 
I haven't touch VEINS in the last year, so I don't know if now things are different. 
When I did it, I manually created it to fit my needs.

**Comment by thardes2** [comment]
There were a lot of changes in Veins within the previous weeks, but the layout of the launchd hasn't changed. The config from Rens should still work.

**Comment by joakimb** [comment]
Thank you! This helps.
