### ISSUE TITLE
Very long routeLength for some vehicles

### ISSUE THREAD

**Issue by danpittphd** [lcodeca/LuSTScenario#9]
Hi,

I downloaded the latest version of the LuST scenario and I ran it on SUMO 1.2. When I checked the results, I found out that the route length for some vehicles is a very large number. I checked further and it looks like this is the case for some vehicles across all 4 cases, included in the scenario:

 grep 17976931348 dua.static.tripinfo.xml  | grep c1carIn32725
    <tripinfo id="c1carIn32725:1" depart="46563.00" departLane="-30762#0_0" departPos="896.28" departSpeed="0.00" departDelay="0.00" arrival="46564.00" arrivalLane="-30762#0_0" arrivalPos="222.90" arrivalSpeed="0.00" duration="1.00" **routeLength="179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00**" waitingTime="1.00" waitingCount="1" stopTime="0.00" timeLoss="1.00" rerouteNo="0" devices="tripinfo_c1carIn32725:1 routing_c1carIn32725:1" vType="passenger1" speedFactor="1.00" vaporized=""/>
    <tripinfo id="c1carIn32725:3" depart="72253.00" departLane="-30762#0_0" departPos="725.21" departSpeed="0.00" departDelay="0.00" arrival="72254.00" arrivalLane="-30762#0_0" arrivalPos="526.77" arrivalSpeed="0.00" duration="1.00" **routeLength="179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00**" waitingTime="1.00" waitingCount="1" stopTime="0.00" timeLoss="1.00" rerouteNo="0" devices="tripinfo_c1carIn32725:3 routing_c1carIn32725:3" vType="passenger2b" speedFactor="0.92" vaporized=""/>

grep 17976931348 due.static.tripinfo.xml  | grep c1carIn32725
    <tripinfo id="c1carIn32725:3" depart="72253.00" departLane="-30762#0_0" departPos="485.00" departSpeed="0.00" departDelay="0.00" arrival="72254.00" arrivalLane="-30762#0_0" arrivalPos="407.84" arrivalSpeed="0.00" duration="1.00" **routeLength="179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00"** waitingTime="1.00" waitingCount="1" stopTime="0.00" timeLoss="1.00" rerouteNo="0" devices="tripinfo_c1carIn32725:3" vType="passenger2b" speedFactor="0.92" vaporized=""/>

grep 17976931348 due.actuated.tripinfo.xml  | grep c1carIn32725
    <tripinfo id="nrh01c1carIn32725:1" depart="46563.00" departLane="-30762#0_0" departPos="1002.74" departSpeed="0.00" departDelay="0.00" arrival="46564.00" arrivalLane="-30762#0_0" arrivalPos="877.28" arrivalSpeed="0.00" duration="1.00" **routeLength="179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00"** waitingTime="1.00" waitingCount="1" stopTime="0.00" timeLoss="1.00" rerouteNo="0" devices="tripinfo_nrh01c1carIn32725:1" vType="passenger1" speedFactor="1.10" vaporized=""/>

grep 17976931348 dua.actuated.tripinfo.xml  | grep c1carIn32725
    <tripinfo id="nrh01c1carIn32725:1" depart="46563.00" departLane="-30762#0_0" departPos="887.69" departSpeed="0.00" departDelay="0.00" arrival="46564.00" arrivalLane="-30762#0_0" arrivalPos="143.21" arrivalSpeed="0.00" duration="1.00" **routeLength="179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00"** waitingTime="1.00" waitingCount="1" stopTime="0.00" timeLoss="1.00" rerouteNo="0" devices="tripinfo_nrh01c1carIn32725:1" vType="passenger1" speedFactor="1.10" vaporized=""/>

grep 17976931348 dua.static.tripinfo.xml  | wc -l
563

grep 17976931348 due.static.tripinfo.xml  | wc -l
533

grep 17976931348 dua.actuated.tripinfo.xml  | wc -l
541

grep 17976931348 due.actuated.tripinfo.xml  | wc -l
545

Do you have any explanation what causes these results?

**Comment by lcodeca** [comment]
The scenario has been generated with SUMO version 0.26 and validated with real data. 
It has not been tested with any recent version of SUMO. 
I don't know, and given the massive amount of changes in SUMO, I cannot help.

**Comment by danpittphd** [comment]
Thank you!
